* O que é isso?

  Este é um script de instalação fácil para CloudStack 4.x.
  Este scrip automatiza a instalação em um novo node CentOS 6.x minimal.
  Tudo que você tem a fazer é executar esse script com opções '-canm'.
  Depois de algum tempo você vai ver mensagem de boas-vindas no CloudStack web UI.

  Este script também economiza etapas de instalação de CloudStack em múltiplos nodes
  com Management Servers, Computing Nodes and Storage Servers.

* Como usar

  Faça o download deste script para onde quiser no servidor que CloudStack será instalado.
  Quando você executar este script com '-h'(help) opção, você vai ver as opções disponíveis para o script.
  : ./autoinstall_cloudstack.sh -h

** Opções
     | Opção  | Função                                 |
     | -c     | instalar pacotes comuns                |
     | -n     | instalar NFS server                    |
     | -a     | instalar o agente para computing nodes |
     | -m     | instalar o Management Server           |
     | -h     | exibir ajuda                           |
     | -r     | reiniciar após a instalação            |
     Uso:
       - '-cm': quando você quiser instalar apenas o management server
       - '-cn': quando você quiser instalar apenas o NFS server
       - '-ca': quando você quiser instalar apenas o agente para computing nodes
     A '-c'(common) opção definirá SELinux para permissive, firewall and network.

     Instalando CloudStack on único node, digite o comando abaixo:
     : ./autoinstall_cloudstack.sh -cnamr

** Dicas
  - Você vai precisar instalar 'wget' ou pacote 'openssh-clients' com o comando yum antes de baixar esse script.
  - Se você quiser economizar tempo para as credenciais de entrada para acessar por SSH, insira a chave pública ssh da sua máquina cliente em SSH_PUBLIC_KEY na 3ª linha do script (opcional).

* Preocupações
  Este script configura a rede para os requisitos CloudStack automaticamente e poderá funciona apenas em servidores com 1 NIC. 

  Este script configura bridges de rede como:
  : # brctl show
  : bridge name bridge id               STP enabled     interfaces
  : cloud0      8000.fe00a9fe0074       no              vnet0
  :                                                     vnet3
  : cloudbr0    8000.80ee733704b5       no              eth0
  :                                                     vnet1
  :                                                     vnet2
  :                                                     vnet4
  :                                                     vnet5
  :                                                     vnet6
  : virbr0      8000.52540079e395       yes             virbr0-nic

* Passos para instalar CloudStack em único servidor
  - Instalar o CentOS 6.X minimal.
  - Instalar e configurar CloudStack
    : yum install wget -y
    : wget http://bit.ly/AutoCSsh
    : sh ./autoinstall_cloudstack.sh -cnmar
  - Inserir informações que são necessárias para a instalação, como hostname e endereço de ip.
  - O management server será reiniciado automaticamente. Após reiniciar,
    acesse "http://YOUR-MANAGEMENT-SERVER-IP:8080/client" usando o navegador web em uma máquina cliente.
  - Digite o nome de usuário e senha abaixo.
    + username: admin
    + password: password
  - Inseir as informações do seu cloud através do Wizard.
  - *!NÃO ESQUEÇA!* Depois de criar uma zona, reinicie o SecondaryStorageVM.
  - Acesse Infrastructure => System VMs => s-1-VM => click Reboot System VM button (ícone da seta girando)
  - Acesse Templates => CentOS 5.5 => Espere até o status "Ready" mudar para "Yes".
